---
# Source: kubernetes-external-secrets/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-kubernetes-external-secrets
  namespace: "external-secrets"
  labels:
    app.kubernetes.io/name: kubernetes-external-secrets
    helm.sh/chart: kubernetes-external-secrets-8.3.2
    app.kubernetes.io/instance: test
    app.kubernetes.io/managed-by: Helm
